<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>text1</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>c1fd54d0-a121-4b1e-bff9-1ce213b988c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>45854800-eb1e-4890-91f7-df02267e094a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. </value>
      <webElementGuid>1ee83db5-1c73-476d-8f1b-20197f056ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>io.appium.android.apis:id/text1</value>
      <webElementGuid>22845c5c-0468-465c-a602-891dfc614c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>io.appium.android.apis</value>
      <webElementGuid>ee187daf-7e5d-486b-9f42-691071dce2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. </value>
      <webElementGuid>511408bd-031e-44c8-b763-f5d424a781fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55c1f473-9ef7-47b1-98b8-d80d2802e31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c91fec3-9970-4bc7-86c1-f0e049d1822b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c7463edf-9f6a-4fc7-982f-27cef36caf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0716778-4e52-4fba-b38d-38b06c938482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ccc7e0de-3921-45b5-b52d-9631866515f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>00bdb49c-9ae5-4c79-a0bf-cf4d77e40870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b0a2c56-5a8e-4747-b127-7fd9b6e65d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c7ef548-cae8-4fd7-8175-9c656b4acc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd652b01-8b31-451c-89a4-462ed53610da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8ca8eec-c028-4d99-afd1-86e2ee02b995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ff7c92c-cc44-40e9-9a5e-d93b6b29a28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>220</value>
      <webElementGuid>82ff00a5-6065-48cf-a653-b01e674aeb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1800</value>
      <webElementGuid>cf570798-4168-45ac-8582-d06ccee1026f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>452</value>
      <webElementGuid>64151349-30a0-4e3e-a2b5-0125ee7601f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>90eaa7ee-a779-41a6-aadf-1174761cac4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-important</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1448052d-6750-4d5e-ac57-a9e120f169a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[0,220][1800,672]</value>
      <webElementGuid>a935c0e6-91aa-41a8-bafd-5abfa6c3d638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fbcb16ee-7257-4719-9165-9a30712d0c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>context-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44af1344-efcb-4dad-9ebf-caf91cc6d9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dismissable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71a1e63d-60e2-435e-ac83-32008919cdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a88545f4-3aeb-48ff-ab81-60ba4ba92ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>drawing-order</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>69f1ef58-6291-4889-89f4-6f4717a5ebfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>heading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2923124-5e7b-48f6-b8fd-2f8280eba92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>live-region</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>320c98ed-00fa-4131-8b89-00acc63d7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>screen-reader-focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fd91cd0-661a-46ef-8f18-79120adf4dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showing-hint</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4a2054c-b472-4822-a5cd-99ff8ecbf3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-entry-key</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>450570cf-e1d0-4c49-9ab0-41c166065b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-has-clickable-span</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf7e4044-38ad-46bc-b03a-92638ba44f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.FrameLayout[2]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.TextView[1]</value>
      <webElementGuid>098e1c92-ee5a-46b1-8fd9-8b88732f2878</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = 'text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. ' or . = 'text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. ') and @resource-id = 'io.appium.android.apis:id/text1']</locator>
   <locatorCollection>
      <entry>
         <key>NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>android.widget.TextView</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@class = 'android.widget.TextView' and (@text = 'text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. ' or . = 'text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. ') and @resource-id = 'io.appium.android.apis:id/text1']</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>io.appium.android.apis:id/text1</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. </value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().className(&quot;android.widget.TextView&quot;).text(&quot;text1: Various kinds of data that will be auto-linked. In this text are some things that are actionable. For instance, you can click on http://www.google.com and it will launch the web browser. You can click on google.com too. If you click on (415) 555-1212 it should dial the phone. Or just write foobar@example.com for an e-mail link. If you have a URI like http://www.example.com/lala/foobar@example.com you should get the full link not the e-mail address. Or you can put a location like 1600 Amphitheatre Parkway, Mountain View, CA 94043. To summarize: https://www.google.com, or 650-253-0000, somebody@example.com, or 9606 North MoPac Expressway, Suite 400, Austin, TX 78759. &quot;).resourceId(&quot;io.appium.android.apis:id/text1&quot;)</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//hierarchy/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.FrameLayout[2]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.TextView[1]</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
